---
swagger: "2.0"
info:
  description: "Metadata API"
  version: "0.1.0"
  title: "Jtree Metadata API"
  contact:
    email: "info@distributedgenomics.ca"
  license:
    name: "GPL"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
host: "virtserver.swaggerhub.com"
basePath: "/Jtree/metadata/0.1.0"
schemes:
- "http"
paths:
  /individuals/search:
    get:
      summary: "searches individuals"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ individuals\n"
      operationId: "searchIndividual"
      produces:
      - "application/json"
      parameters:
      - name: "searchString"
        in: "query"
        description: "pass an optional search string for looking up inventory"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Individual"
        400:
          description: "bad input parameter"

  /individual/{individualId}:
    parameters:
    - name: "individualId"
      in: "path"
      required: true
      type: "string"
    get:
      summary: "Returns an individual by ID."
      operationId: "getIndividual"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Individual"
        404:
          description: "individual not found"

  /individual:
    post:
      summary: "adds an individual item"
      description: "Adds an individual to the system"
      operationId: "addIndividual"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "individual"
        description: "Individual"
        required: false
        schema:
          $ref: "#/definitions/Individual"
      responses:
        201:
          description: "item created"
        400:
          description: "invalid input, object invalid"
        409:
          description: "an existing item already exists"

  /biosamples/search:
    get:
      summary: "searches biosamples"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ biosample\n"
      operationId: "searchBiosample"
      produces:
      - "application/json"
      parameters:
      - name: "searchString"
        in: "query"
        description: "pass an optional search string for looking up inventory"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Biosample"
        400:
          description: "bad input parameter"

  /biosample/{biosampleId}:
    parameters:
    - in: path
      name: biosampleId
      required: true
      type: string
    get:
      summary: "Returns an biosample by ID."
      operationId: "getBiosample"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Biosample"
        404:
          description: "Biosample not found"

  /biosample:
    post:
      summary: "adds a biosample"
      description: "Adds a biosample to the system"
      operationId: "addBiosample"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "biosample"
        description: "Biosample"
        required: false
        schema:
          $ref: "#/definitions/Biosample"
      responses:
        201:
          description: "item created"
        400:
          description: "invalid input, object invalid"
        409:
          description: "an existing item already exists"

definitions:
  OntologyTerm:
    type: "object"
    required:
    - "term"
    - "termId"
    properties:
      termId:
        type: "string"
        example: "PATO:0020001"
      term:
        type: "string"
        example: "male genotypic sex"
      ontology:
        type: "string"
        format: "url"
        example: "http://purl.obolibrary.org/obo"
    example:
      termId: "PATO:0020001"
      term: "male genotypic sex"
      ontology: "http://purl.obolibrary.org/obo"
  Attribute:
    type: "object"
    additionalProperties:
      type: "string"
  Attributes:
    type: "array"
    items:
      $ref: "#/definitions/Attribute"
  Individual:
    type: "object"
    required:
    - "description"
    - "name"
    properties:
      id:
        type: "string"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      name:
        type: "string"
        example: "jtree-BCGSC-IN-d290f1ee-6c54-4b01-90e6"
      description:
        type: "string"
      createdDate:
        type: "string"
        format: "date"
      updatedDate:
        type: "string"
        format: "date"
      species:
        $ref: "#/definitions/OntologyTerm"
      sex:
        $ref: "#/definitions/OntologyTerm"
      attributes:
        $ref: "#/definitions/Attributes"
    example:
      createdDate: "2000-01-23"
      species:
        termId: "PATO:0020001"
        term: "male genotypic sex"
        ontology: "http://purl.obolibrary.org/obo"
      sex:
        termId: "PATO:0020001"
        term: "male genotypic sex"
        ontology: "http://purl.obolibrary.org/obo"
      name: "jtree-BCGSC-IN-d290f1ee-6c54-4b01-90e6"
      description: "description"
      attributes: ""
      id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      updatedDate: "2000-01-23"
  Biosample:
    type: "object"
    required:
    - "collectionAge"
    - "description"
    - "individualId"
    - "name"
    properties:
      id:
        type: "string"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      name:
        type: "string"
        example: "jtree-BCGSC-SM-d290f1ee-6c54-4b01-90e6"
      description:
        type: "string"
      disease:
        $ref: "#/definitions/OntologyTerm"
      createdDate:
        type: "string"
        format: "date"
      updatedDate:
        type: "string"
        format: "date"
      individualId:
        type: "string"
      attributes:
        $ref: "#/definitions/Attributes"
      collectionAge:
        type: "string"
    example:
      disease:
        termId: "PATO:0020001"
        term: "male genotypic sex"
        ontology: "http://purl.obolibrary.org/obo"
      createdDate: "2000-01-23"
      name: "jtree-BCGSC-SM-d290f1ee-6c54-4b01-90e6"
      description: "description"
      attributes: ""
      id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      updatedDate: "2000-01-23"
      individualId: "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
      collectionAge: "collectionAge"
